### ISSUE TITLE
failures running in headless session

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/Biomass_speciesData#32]
Using `.plots = c("object", "png", "raw")` in headless session (w/o using `xvfb`) fails with the following cairo graphics error:

```r
Oct20 09:03:00 Biomass_speciesData    total elpsd: 6.2 secs | 0 Biomass_speciesData ini
2022-10-20 09:03:00 WARNING::message call unable to open connection to X11 display '' x11()
2022-10-20 09:03:00 ERROR::e: unable to start device X11cairo
 2022-10-20 09:03:00 ERROR::e: .External2(C_X11, d$display, d$width, d$height, d$pointsize, d$gamma, d$colortype, d$maxcubesize, d$bg, d$canvas, d$fonts, NA, d$xpos, d$ypos, d$title, type, antialias, d$family, optionSymbolFont(d$symbolfamily))
Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  : 
  unable to start device X11cairo
```

I can presumably get around this by starting my R session using `xvfb-run -a R` or similar, but this imposes addional system dependencies (which user may not have ability to install) and adds an extra layer to the run requirements of this module, which impacts all LandR Biomass sims.

@CeresBarros I know I prefer cairo graphics in some cases, but are they essential here?

**Comment by achubaty** [comment]
At the very least, we should try to identify if `isTRUE(capabilities("X11"))` (Linux only?) and give the user a meaningful error message, with instructions on how to run R using `xvfb`.

**Comment by CeresBarros** [comment]
Also, I wasn't the one implementing plotting on B_sppData, so I can't answer your question as I personally have no strong preference.
In any case, plotting in B_sppData uses `LandR::plotVTM`, which uses `Plot` (not `Plots`) internally. I think the right fix would be to adapt `plotVTM` to use `Plots` if possible.

**Comment by achubaty** [comment]
yep, `.plots` not used -- i included it b/c i thought it was.

the offending line is `dev.set(newDev)`, not the `plotVTM()` call.

trying to resolve

**Comment by achubaty** [comment]
moving to Plots() would definitely help here

**Comment by CeresBarros** [comment]
Yes I think it would. but wrt to openning a new device, I'll see what we did in B_core, because we deal with that too

**Comment by CeresBarros** [comment]
I believe the answer is to pass `.plots` tio this module too and _not_ open a new device if `.plots` does not contain"screen", as in B_core:
```
if (anyPlotting(P(sim)$.plots) &&
               any(P(sim)$.plots == "screen")) {
             ## if current plot dev is too small, open a new one
             if (is.null(dev.list())) {
               dev(x = dev.cur() + 1, height = 7, width = 14)
               clearPlot()
             } else {
               if (dev.size()[2] < 14) {
                 dev(x = dev.cur() + 1, height = 7, width = 14)
                 clearPlot()
               }
             }
             ## current window will be used for  summary stats
             ## a new one for maps
             mod$statsWindow <- dev.cur()
             if (P(sim)$.plotMaps) {
               mod$mapWindow <- mod$statsWindow + 1
               dev(x = mod$mapWindow, height = 8, width = 10)
             }
           } else {
             ## if plotting is deactivated make sure maps are NOT plotted
             params(sim)[[currentModule(sim)]]$.plotMaps <- FALSE
           }
```

**Comment by CeresBarros** [comment]
plus using `Plots`, of course, but if the above works , then I'd say leave Plot/Plots alone for now

**Comment by achubaty** [comment]
I used a version of the above to resolve this. pushing shortly

**Comment by achubaty** [comment]
closing, but i've added a TODO in the affected code block to switch fully to Plots() so that these wtm maps can be saved as pngs etc. if not plotted to screen.
